require("plugins/nvim-tree")
require("plugins/treesitter")
require("plugins/telescope")
require("plugins/nvim-cmp")
require("plugins/auto-pairs")
require("plugins/comment")
require("plugins/lualine")
require("plugins/which-key")
