require("plugins/nvim-tree")
require("plugins/treesitter")
require("plugins/telescope")
require("plugins/nvim-cmp")
require("plugins/auto-pairs")
require("plugins/comment")
require("plugins/lualine")
require("plugins/which-key")
require("plugins/dadbod")
require("plugins/gitsigns")
require("plugins/lightspeed")
require("plugins/lsp_signature")
require("plugins/neoscroll")
-- require("plugins/rust-tools")
